
INSERT INTO ROLE (role) VALUES ('ROLE_ADMIN')
INSERT INTO ROLE (role) VALUES ('ROLE_USER')
INSERT INTO USERS (login, enabled, password) VALUES ('admin', true, '$2a$10$ZHoQuWNWx.hjhzx088bC0uBhV/Jm9GY0gMdxOOH3wSKUGLL3jKDsy')
INSERT INTO USERS (login, enabled, password) VALUES ('user', true, '$2a$10$oX/eiEdi5iGhSHYyya7O7OXJ2TYUm576.yWkSytgmJXM6Tz9Ll01S')
INSERT INTO USER_ROLE (users_login, role_role) VALUES ('admin', 'ROLE_ADMIN')
INSERT INTO USER_ROLE (users_login, role_role) VALUES ('admin', 'ROLE_USER')
INSERT INTO USER_ROLE (users_login, role_role) VALUES ('user', 'ROLE_USER')
INSERT INTO RESTAURANT (id, name) VALUES (1, 'KFC')
INSERT INTO RESTAURANT (id, name) VALUES (2, 'McDonalds')
INSERT INTO RESTAURANT (id, name) VALUES (3, 'Kumpel')
INSERT INTO MENU (id, date, restaurant_id) VALUES (1, '2015-11-12', 3)
INSERT INTO MENU (id, date, restaurant_id) VALUES (2, '2015-11-12', 2)
INSERT INTO DISH (id, name, price, menu_id) VALUES (1, 'plov', 20.70, 1)
INSERT INTO DISH (id, name, price, menu_id) VALUES (2, 'omlet', 10.00, 1)
INSERT INTO DISH (id, name, price, menu_id) VALUES (3, 'beef', 25.0, 1)
INSERT INTO DISH (id, name, price, menu_id) VALUES (4, 'bread', 0.70, 1)